const React = require("react");
const html = require("htm").bind(React.createElement);

exports.data = {
  layout: "layouts/main.11ty.js",
};

exports.render = (data) => {
  return html`
  <div class="mockup-container">
    <img alt="Browser Mockup" src="../assets/images/browser-mockup.svg"/>
  </div>
    <p>
      This static site is generated by${" "}
      <a href="https://www.11ty.dev/">Eleventy</a>, but it uses React as the
      templating engine.
    </p>
  `;
};